
chains = ["interop-alpha-0", "interop-alpha-1"]
network = "interop-alpha"

[[contracts]]
id = "FlashLoanVault"
salt = "ethers"
forge_artifact_path = "contracts/out/FlashLoanVault.sol/FlashLoanVault.json"

[[contracts]]
id = "CrosschainFlashLoanToken"
salt = "ethers"
forge_artifact_path = "contracts/out/CrosschainFlashLoanToken.sol/CrosschainFlashLoanToken.json"

[[contracts]]
id = "CrosschainFlashLoanBridge"
salt = "ethers"
forge_artifact_path = "contracts/out/CrosschainFlashLoanBridge.sol/CrosschainFlashLoanBridge.json"
constructor_args = [
  "{{CrosschainFlashLoanToken.address}}",
  "{{FlashLoanVault.address}}",
  "10000000000000000",
  "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
]

[[contracts]]
id = "TargetContract"
salt = "ethers"
forge_artifact_path = "contracts/out/TargetContract.sol/TargetContract.json"
